### ISSUE TITLE
Error: ValueError: chr() arg not in range(256)

### ISSUE THREAD

**Issue by flynjets** [dizzythinks/asavpnusers#1]
I'm getting the error below when running in Ubuntu. Any ideas?
Traceback (most recent call last):
  File "./asa.py", line 107, in <module>
    main()
  File "./asa.py", line 98, in main
    users = asa.get_connected_users()
  File "./asa.py", line 18, in get_connected_users
    output = self._convert_ascii_code_to_text(output)
  File "./asa.py", line 58, in _convert_ascii_code_to_text
    username_as_text = ''.join(chr(i) for i in username_as_ascii)
  File "./asa.py", line 58, in <genexpr>
    username_as_text = ''.join(chr(i) for i in username_as_ascii)
ValueError: chr() arg not in range(256)

**Comment by flynjets** [comment]
I figured it out. I changed line 11 to:
self.cmd = 'snmpwalk -v1 -c%s %s 1.3.6.1.4.1.9.9.392.1.3.21.1.10' % (community_string, firewall)

and changed line 35 to:
string_to_remove = 'iso.3.6.1.4.1.9.9.392.1.3.21.1.10.'

I'm not sure why those are different in my case.

Thanks for posting this!

**Comment by dizzythinks** [comment]
I should probably have added that the script was running on Debian where I use it. My guess is its something to do with the different way SNMP is implemented by default on Ubuntu. Also, I have the CISCO MIB installed where I run it too. If you want to make these values arguments and submit a pull request that would be cool. I will look at some better error handling of this as well.
