### ISSUE TITLE
Error executing

### ISSUE THREAD

**Issue by dnietogo** [dizzythinks/asavpnusers#2]
Hi all,

first of all I want to thank you for your apportation to the community. We have an ASA5520 and when we try to execute the script we have this error:

$ python getusers.py -f 192.168.1.1 -c SNMPPublic -o test.txt
Traceback (most recent call last):
  File "getusers.py", line 107, in <module>
    main()
  File "getusers.py", line 98, in main
    users = asa.get_connected_users()
  File "getusers.py", line 16, in get_connected_users
    output = self._get_ascii_codes(output)
  File "getusers.py", line 36, in _get_ascii_codes
    output = [[x[0].replace(string_to_remove,'').strip(' '), x[1]] for x in output]
IndexError: list index out of range

Do you know what kind of problem could be?

Thank you for your support :)

**Comment by dizzythinks** [comment]
Hmmm.. its been a long time since I wrote this script.

Can you put a "print output" after the output = self._commands_output_to_list(output) in the get_connected_users function?

And paste the result?

**Comment by dnietogo** [comment]
Thank you for your fast answer, the output is the same:

$  python getusers.py -f 192.168.1.1 -c SNMPPublic -o test.txt
Traceback (most recent call last):
  File "getusers.py", line 108, in <module>
    main()
  File "getusers.py", line 99, in main
    users = asa.get_connected_users()
  File "getusers.py", line 17, in get_connected_users
    output = self._get_ascii_codes(output)
  File "getusers.py", line 37, in _get_ascii_codes
    output = [[x[0].replace(string_to_remove,'').strip(' '), x[1]] for x in output]
IndexError: list index out of range

**Comment by mdiorio** [comment]
_argument('-o', '--output', action='store', default='json', help='Output type, option are json and text. Defaults to json')

Your issue appears to be -o takes one of two arguments "json" or "text".  You're trying to give it a file name.  You need to pipe the output to a file yourself.

python getusers.py -f 192.168.1.1 -c SNMPPublic -o text >> test.txt

**Comment by dizzythinks** [comment]
Dammit.. I didn't even spot that! Thanks :)

**Comment by dnietogo** [comment]
Sure, now it works! Thank ou mdiorio and dizzy!
