### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by mdiorio** [dizzythinks/asavpnusers#3]
Hi,

Thanks for writing this!  I'm running into an issue when running it.

[root@ghq-1pmonap01 zabbix]# ./vpnusers.py  -f 12.34.56.78 -c public
Traceback (most recent call last):
  File "./vpnusers.py", line 84, in <module>
    main()
  File "./vpnusers.py", line 77, in main
    users = asa.get_connected_users()
AttributeError: ASAVpn instance has no attribute 'get_connected_users'

Thanks!

**Comment by mdiorio** [comment]
Never mind - there was a problem with the indenting when I copied/pasted it.  Ugh - such a simple thing.

**Comment by dizzythinks** [comment]
All working now? Curious to know what Model Cisco device you are using?

**Comment by mdiorio** [comment]
Yup - working fine.  Just going to have it run every few minutes and then pull the results into my Zabbix monitoring system.

We're using ASA 5525's ASA release version 9.5(3)
